### ISSUE TITLE
Error running dharma server

### ISSUE THREAD

**Issue by shubham0d** [MozillaSecurity/dharma#17]
Hi,
I have recently installed dharma using pip. But while running the following command I am facing some issue:
```
$ dharma -grammars grammars/canvas2d.dg -server -template grammars/var/templates/html5/default.html
[Dharma] 2019-05-09 14:48:31,245 INFO: Machine random seed: 62779021592397288
[Dharma] 2019-05-09 14:48:31,246 DEBUG: Using configuration from: /home/hackintosh/.local/lib/python2.7/site-packages/dharma/settings.py
[Dharma] 2019-05-09 14:48:31,247 DEBUG: Processing grammar content of ../../../.local/lib/python2.7/site-packages/dharma/grammars/common.dg
[Dharma] 2019-05-09 14:48:31,250 DEBUG: Processing grammar content of grammars/canvas2d.dg
[Dharma] 2019-05-09 14:48:31,253 WARNING: Line 227 [canvas2d]: Unable to identify argument of uri() "fuzzdata/samples/jpg/"
[Dharma] 2019-05-09 14:48:31,254 INFO: Socket server is listening at 127.0.0.1:9090
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 48738)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/hackintosh/.local/lib/python2.7/site-packages/dharma/core/websocket.py", line 48, in handle
    hresponse = hashlib.sha1(headers['sec-websocket-key'].encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'
```
Can someone explain me what is going wrong?

**Comment by posidron** [comment]
Please use Python 3

**Comment by Vilumbre** [comment]
Hello. 
I'm using python 3.8, which the problem here?

dharma -grammars /home/demian/dharma/dharma/grammars/canvas2d.dg -server -template grammars/var/templates/html5/default.html
[Dharma] 2020-05-01 18:35:06,071 INFO: Machine random seed: -601819454102034061
[Dharma] 2020-05-01 18:35:06,071 DEBUG: Using configuration from: /usr/local/lib/python3.8/dist-packages/dharma-1.3.1-py3.8.egg/dharma/settings.py
[Dharma] 2020-05-01 18:35:06,072 DEBUG: Processing grammar content of ../../../../usr/local/lib/python3.8/dist-packages/dharma-1.3.1-py3.8.egg/dharma/grammars/common.dg
[Dharma] 2020-05-01 18:35:06,077 DEBUG: Processing grammar content of /home/demian/dharma/dharma/grammars/canvas2d.dg
[Dharma] 2020-05-01 18:35:06,081 WARNING: Line 227 [canvas2d]: Unable to identify argument of uri() "fuzzdata/samples/jpg/"
[Dharma] 2020-05-01 18:35:06,082 INFO: Socket server is listening at 127.0.0.1:9090

---------------------------------------------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51394)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/dharma-1.3.1-py3.8.egg/dharma/core/websocket.py", line 48, in handle
    hresponse = hashlib.sha1(headers['sec-websocket-key'].encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'
